@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
Person(зоотехник, "Зоотехник", "Следит за животными")
Person(директор, "Директор хозяйства", "Управление через веб-портал")
Person(механик, "Механик", "Мониторинг техники")
Person(дежурный_оператор, "Дежурный оператор", "Управление оффлайн-уведомлениями")

System_Boundary(mvp_границы, "Границы MVP для ферм") {
    ' === Внутренние системы ===
    System(mvp_платформа, "MVP Платформа Мониторинга Скота", "Центральный сервер + агенты на фермах", "Микросервисная архитектура с видеоаналитикой и IoT")
    ' === Внешние системы ===
    System_Ext(api_client, "Мобильное/Веб-приложение", "Для ролей/аутентификации", "REST API")
    System_Ext(локальный_сервис_фермы, "Локальный сервис на ферме", "Предварительная обработка (оффлайн)", "Кэш видео/данных, обработка нейросетью")
}

System_Boundary(облачный_сервис_границы,"Границы облачного сервиса") {
    System(yandex_cloud, "Облачный сервис", "Хранение и обработка данных", "Масштабируемое хранение данных")
}
' === Внутренние системы ===
System(аграрная_платформа, "АгроПром Х - Цифровая платформа", "Центральная аграрная платфома", "Микросервисная архитектура")

' === Взаимосвязи ===
Rel(директор, mvp_платформа, "Использует", "Отслеживает показатели фермы")
Rel(зоотехник, mvp_платформа, "Использует", "Мониторинг и оповещение (беспокойство, болезнь)", "Push + SMS")
Rel(механик, mvp_платформа, "Мониторит", "Проверяет состояние оборудования")
Rel(дежурный_оператор, mvp_платформа, "Контролирует", "Локальные оповещения (оффлайн)")
Rel(mvp_платформа, локальный_сервис_фермы, "Передача данных", "Предварительная обработка и временное хранение (Офлайн)")
Rel(локальный_сервис_фермы, дежурный_оператор, "Локальное оповещение", "'Драка в загоне X' + сохранение видео (<5 сек, без WiFi)", "SMS/локальный alarm")
Rel_D(локальный_сервис_фермы, yandex_cloud, "Синхронизация после по WiFi", "Видео/события (поведение, поголовье) в хранение", "HTTPS/MQTT, до 10 мин")
Rel_D(yandex_cloud, аграрная_платформа, "Передача метрик (поголовье, запасы, фильтрация воды)", "Kafka Protocol")
Rel(yandex_cloud, зоотехник, "Глубокий анализ", "Болезнь/прогноз", "Push")
Rel(yandex_cloud, api_client, "Доступ к данным", "OAuth/JWT").

@enduml